version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"

  userservice:
    build: ./backend/userservice
    container_name: userservice
    ports:
      - "8001:8001"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/userdb
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo

  ticketservice:
    build: ./backend/ticketservice
    container_name: ticketservice
    ports:
      - "8002:8002"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/ticketdb
      - SMTP_HOST=${SMTP_HOST:-smtp.gmail.com}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_FROM=${SMTP_FROM:-TicketApp <no-reply@ticketapp.com>}
      - PAYPAL_CLIENT_ID=${PAYPAL_CLIENT_ID}
      - PAYPAL_CLIENT_SECRET=${PAYPAL_CLIENT_SECRET}
      - PAYPAL_MODE=${PAYPAL_MODE:-sandbox}
      - USER_SERVICE_URL=http://userservice:8001
      - EVENT_SERVICE_URL=http://eventservice:8003
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    depends_on:
      - mongo
  
  locationservice:
    build: ./backend/locationservice
    container_name: locationservice
    ports:
      - "8004:8004"
    environment:
      - MONGODB_URI_LOCATION=mongodb://mongo:27017/locationdb
      - MONGODB_URI_SEATMAP=mongodb://mongo:27017/seatmapdb
    depends_on:
      - mongo

  eventservice:
    build: ./backend/eventservice
    container_name: eventservice
    ports:
      - "8003:8003"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/eventdb
      - TICKET_SERVICE_URL=http://ticketservice:8002
      - LOCATION_SERVICE_URL=http://locationservice:8004
      - SMTP_HOST=${SMTP_HOST:-smtp.gmail.com}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_FROM=${SMTP_FROM:-TicketApp <no-reply@ticketapp.com>}
      - USER_SERVICE_URL=http://userservice:8001
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    depends_on:
      - mongo
      - ticketservice
      - locationservice

  gateway:
    build: ./backend/gatewayservice
    container_name: gateway
    ports:
      - "8000:8000"
    environment:
      - USER_SERVICE_URL=http://userservice:8001
      - TICKET_SERVICE_URL=http://ticketservice:8002
      - EVENT_SERVICE_URL=http://eventservice:8003
      - LOCATION_SERVICE_URL=http://locationservice:8004
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - userservice
      - ticketservice
      - eventservice
      - locationservice

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_API_URL=http://gateway:8000
      - REACT_APP_API_ENDPOINT=${REACT_APP_API_ENDPOINT:-http://localhost:8000}
      - REACT_APP_PAYPAL_CLIENT_ID=${REACT_APP_PAYPAL_CLIENT_ID}
      - REACT_APP_PAYPAL_ENVIRONMENT=${REACT_APP_PAYPAL_ENVIRONMENT:-sandbox}
    depends_on:
      - gateway
